In [1]:
#import dependencies

import pandas as pd

In [2]:
#reading in CSV File

death = "CSV Files/hiv-death-rates-by-age.csv"
death_df = pd.read_csv(death)
death_df.head()

,Entity,Code,Year,"Under-5s (per 100,000)","All ages (per 100,000)","70+ years old (per 100,000)","5-14 years old (per 100,000)","15-49 years old (per 100,000)","50-69 years old (per 100,000)","Age-standardized (per 100,000)"
0,Afghanistan,AFG,1990,0.459374,0.320777,0.522788,0.008302,0.348175,0.645751,0.401954
1,Afghanistan,AFG,1991,0.513430,0.360964,0.544811,0.010046,0.387765,0.736372,0.458584
2,Afghanistan,AFG,1992,0.588480,0.412686,0.591638,0.012039,0.436061,0.868626,0.542512
3,Afghanistan,AFG,1993,0.651371,0.408342,0.629242,0.013891,0.401412,0.837047,0.533607
4,Afghanistan,AFG,1994,0.692321,0.435647,0.667779,0.016394,0.428321,0.868039,0.562373

In [3]:
#filtering death by age csv on the year

death_five_years = death_df.loc[death_df["Year"] >= 2013]

death_five_years

,Entity,Code,Year,"Under-5s (per 100,000)","All ages (per 100,000)","70+ years old (per 100,000)","5-14 years old (per 100,000)","15-49 years old (per 100,000)","50-69 years old (per 100,000)","Age-standardized (per 100,000)"
23,Afghanistan,AFG,2013,1.086478,0.688092,0.698738,0.046499,0.892967,1.331047,0.884129
24,Afghanistan,AFG,2014,1.201211,0.722509,0.684093,0.047263,0.908938,1.383621,0.909027
25,Afghanistan,AFG,2015,1.355830,0.782104,0.675140,0.048659,0.963127,1.442483,0.962598
26,Afghanistan,AFG,2016,1.501508,0.848051,0.658624,0.049436,1.032328,1.518304,1.026573
27,Afghanistan,AFG,2017,1.708494,0.919705,0.645646,0.054208,1.086405,1.570305,1.087497
51,Albania,ALB,2013,0.057734,0.053984,0.029190,0.007132,0.062097,0.072189,0.051866
52,Albania,ALB,2014,0.057699,0.052500,0.026483,0.007238,0.060640,0.068463,0.050293
53,Albania,ALB,2015,0.058245,0.053244,0.024745,0.007197,0.062538,0.067452,0.050891
54,Albania,ALB,2016,0.060590,0.049794,0.022893,0.007773,0.058700,0.060160,0.047864
55,Albania,ALB,2017,0.058034,0.046483,0.021701,0.007960,0.055542,0.053696,0.044813
79,Algeria,DZA,2013,1.907159,1.042632,0.706220,0.087663,1.052422,1.580332,1.034755
80,Algeria,DZA,2014,2.131177,1.052536,0.733642,0.091812,1.027111,1.539290,1.035149
81,Algeria,DZA,2015,1.338745,0.947159,0.759385,0.074819,1.006383,1.498959,0.930471
82,Algeria,DZA,2016,0.956929,0.877571,0.778176,0.069423,0.969819,1.443260,0.858558
83,Algeria,DZA,2017,0.767095,0.807293,0.779322,0.078741,0.903857,1.334386,0.785515
107,American Samoa,ASM,2013,0.282254,0.561841,0.335952,0.053604,0.838995,0.695826,0.598527
108,American Samoa,ASM,2014,0.334401,0.576268,0.320917,0.055783,0.850211,0.697143,0.613334
109,American Samoa,ASM,2015,0.353548,0.588898,0.307731,0.057864,0.863541,0.701890,0.626647
110,American Samoa,ASM,2016,0.370462,0.603478,0.295690,0.059611,0.880332,0.710606,0.641862
111,American Samoa,ASM,2017,0.251578,0.603556,0.286217,0.040767,0.902395,0.724917,0.642657
135,Andean Latin America,NaN,2013,16.277638,7.344217,2.461674,0.838162,8.390474,6.762769,7.311287
136,Andean Latin America,NaN,2014,16.812463,7.832191,2.839917,0.855633,9.027741,7.249767,7.786178
137,Andean Latin America,NaN,2015,16.518861,7.856179,2.877595,0.869827,9.099616,7.371294,7.804504
138,Andean Latin America,NaN,2016,16.519956,7.827586,2.737118,0.918744,9.131418,7.124161,7.765193
139,Andean Latin America,NaN,2017,16.829971,7.576942,2.605612,0.991650,8.731841,6.669942,7.507378
163,Andorra,AND,2013,0.082481,0.991452,1.266296,0.009747,0.750611,2.055143,0.698271
164,Andorra,AND,2014,0.087266,0.916403,1.221957,0.009188,0.676048,1.867682,0.639735
165,Andorra,AND,2015,0.102368,0.827316,1.120977,0.008682,0.611886,1.633441,0.575922
166,Andorra,AND,2016,0.135789,0.662528,0.882791,0.008411,0.505089,1.239590,0.463691
167,Andorra,AND,2017,0.157985,0.552723,0.731709,0.008102,0.432047,0.983178,0.389653
...,...,...,...,...,...,...,...,...,...,...
6323,Western Europe,NaN,2013,0.185856,0.887482,0.197460,0.051130,1.047082,1.484844,0.700792
6324,Western Europe,NaN,2014,0.174166,0.777877,0.171133,0.046300,0.886335,1.356553,0.614636
6325,Western Europe,NaN,2015,0.203230,0.822455,0.186358,0.051434,0.936632,1.422735,0.652092
6326,Western Europe,NaN,2016,0.182294,0.819487,0.170519,0.049171,0.997037,1.314434,0.656529
6327,Western Europe,NaN,2017,0.175164,0.796238,0.162292,0.046789,0.987185,1.251898,0.641559
6351,Western Sub-Saharan Africa,NaN,2013,36.838421,78.371558,56.007339,8.205531,126.116712,144.644370,104.280813
6352,Western Sub-Saharan Africa,NaN,2014,46.212309,75.262309,52.140078,7.810320,117.318292,137.781939,98.723118
6353,Western Sub-Saharan Africa,NaN,2015,43.966908,70.620035,48.360958,7.127551,109.553103,131.352419,92.619136
6354,Western Sub-Saharan Africa,NaN,2016,34.682620,64.465888,43.778347,6.760447,101.215745,122.552144,85.073515
6355,Western Sub-Saharan Africa,NaN,2017,31.496535,59.218612,38.392631,6.933828,92.566533,111.854977,77.676690
6379,World,OWID_WRL,2013,16.698674,17.818819,3.919379,3.869058,24.909750,15.050008,17.316935
6380,World,OWID_WRL,2014,16.235424,16.278096,3.604816,3.731628,22.596092,13.618511,15.834777
6381,World,OWID_WRL,2015,14.591026,15.013197,3.499378,3.508225,20.835700,12.778342,14.606885
6382,World,OWID_WRL,2016,12.432021,13.790437,3.377311,3.385997,19.208513,11.933154,13.396183
6383,World,OWID_WRL,2017,11.384021,12.492585,3.123427,3.450465,17.284702,10.820929,12.141835
6407,Yemen,YEM,2013,1.763288,1.120466,1.149132,0.089351,1.359462,1.931347,1.321331
6408,Yemen,YEM,2014,1.742473,1.102179,1.077564,0.087085,1.346277,1.852487,1.286144
6409,Yemen,YEM,2015,1.813014,1.126166,1.035766,0.084531,1.379008,1.841331,1.299472
6410,Yemen,YEM,2016,1.770417,1.143407,1.037933,0.076221,1.429723,1.879008,1.320076
6411,Yemen,YEM,2017,2.455187,1.272229,1.054008,0.104160,1.456742,1.873255,1.402170
6435,Zambia,ZMB,2013,120.155389,199.469151,45.192114,51.356007,317.992056,221.224607,240.309368
6436,Zambia,ZMB,2014,116.886018,170.421320,35.262820,53.990268,261.070324,177.100671,197.717641
6437,Zambia,ZMB,2015,123.766626,147.238333,32.888584,47.315824,214.564534,165.015272,168.271118
6438,Zambia,ZMB,2016,131.302199,130.717129,31.882492,41.286065,181.241580,157.845314,147.361133
6439,Zambia,ZMB,2017,161.580937,125.585775,31.362699,42.688354,159.560883,153.241286,137.761161
6463,Zimbabwe,ZWE,2013,73.190024,232.844127,58.371777,47.859598,382.799694,264.801072,278.365351
6464,Zimbabwe,ZWE,2014,45.646260,176.829798,46.709054,46.237139,286.520766,209.658047,208.990701
6465,Zimbabwe,ZWE,2015,42.129426,147.030397,44.885665,42.616850,230.404581,195.674105,173.987398
6466,Zimbabwe,ZWE,2016,43.233945,128.037227,43.596335,46.296246,190.406941,186.366985,150.980630
6467,Zimbabwe,ZWE,2017,36.095186,109.185795,43.174810,36.834084,159.618584,180.615909,130.353613

In [4]:
# Rename the headers to be more explanatory
renamed_death_df = death_five_years.rename(columns={"Under-5s (per 100,000)": "(1-4)",
                                       "70+ years old (per 100,000)": "(70+)",
                                        "5-14 years old (per 100,000)": "(5-14)",
                                        "15-49 years old (per 100,000)": "(15-49)",
                                        "50-69 years old (per 100,000)": "(50-69)"
                                        })


renamed_death_df.head()

,Entity,Code,Year,(1-4),"All ages (per 100,000)",(70+),(5-14),(15-49),(50-69),"Age-standardized (per 100,000)"
23,Afghanistan,AFG,2013,1.086478,0.688092,0.698738,0.046499,0.892967,1.331047,0.884129
24,Afghanistan,AFG,2014,1.201211,0.722509,0.684093,0.047263,0.908938,1.383621,0.909027
25,Afghanistan,AFG,2015,1.355830,0.782104,0.675140,0.048659,0.963127,1.442483,0.962598
26,Afghanistan,AFG,2016,1.501508,0.848051,0.658624,0.049436,1.032328,1.518304,1.026573
27,Afghanistan,AFG,2017,1.708494,0.919705,0.645646,0.054208,1.086405,1.570305,1.087497

In [5]:
#only select the columns needed from dataframe 

renamed_death_df = renamed_death_df[["Entity", "Year", "(1-4)", "(5-14)",
                                    "(15-49)", "(50-69)", "(70+)"]]

renamed_death_df.head()

         Entity  Year     (1-4)    (5-14)   (15-49)   (50-69)     (70+)
23  Afghanistan  2013  1.086478  0.046499  0.892967  1.331047  0.698738
24  Afghanistan  2014  1.201211  0.047263  0.908938  1.383621  0.684093
25  Afghanistan  2015  1.355830  0.048659  0.963127  1.442483  0.675140
26  Afghanistan  2016  1.501508  0.049436  1.032328  1.518304  0.658624
27  Afghanistan  2017  1.708494  0.054208  1.086405  1.570305  0.645646

In [8]:
#push the remade DataFrame to a new CSV file
renamed_death_df.to_csv("CSV Files/death_age_2013_to_2017.csv",
                  encoding="utf-8", index=False, header=True)